### ISSUE TITLE
The problem with git-lfs.... 

### ISSUE THREAD

**Issue by pombredanne** [frostming/pdm-packer#16]
Unless  git-lfs  is installed (and configured possibly requiring extra paid services from GitHub) a plain git clone of this repo fails.
This is creating problems like @kloczek reported in https://github.com/pdm-project/pdm/issues/1084

And I reckon that your position is https://github.com/pdm-project/pdm/issues/1084#issuecomment-1131407250

> Checking in binary files in a git repository is not a good practice. Because Git will store all histories in the .git directory, if the file is a binary the storage is not efficient: it can't store the delta changes like a plain text file.

I understand your point, but here this is eventually creating difficulties for any adopter and aspiring contributor. IMHO this may not be the effect you are looking for? The whole set of wheels and archives is about 3.1MB total and this are binaries but not what I would call large files.

I would suggest to consider using something else:
- just copy the test wheels inside the repo... these are not super big and not evolving quickly
- or use a separate repo just for the test wheels and use git modules to get it
- or put these in a tarball under a release of this repo and fetch these from there

**Comment by pombredanne** [comment]
Note that because of this I cannot just get a plain git clone working.

**Comment by frostming** [comment]
> or put these in a tarball under a release of this repo and fetch these from there

Oh, that is a good suggestion. But anyway this issue seems not related to this project, I will close it. Let's track it in https://github.com/pdm-project/pdm/issues/1084

**Comment by pombredanne** [comment]
I filed this in the wrong project alright! Sorry for this
