### ISSUE TITLE
[QUESTION]. how to use it?

### ISSUE THREAD

**Issue by vitidev** [frostming/pdm-packer#19]
I created a test project

    pdm init 

add `run.py`

    def run():
        print('hello')

pack

    pdm pack -m run:run -o app.zip -v
    Packing packages...
    All packages are synced to date, nothing to do.

      All complete!
    Packages are prepared at U:\Temp\pdm-pack-a64tsc6l\lib
    Creating zipapp...
    Traceback (most recent call last):
      File "C:\Python\lib\runpy.py", line 196, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "C:\Python\lib\runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "c:\users\user\.local\bin\pdm.exe\__main__.py", line 7, in <module>
      File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 254, in main
        return Core().main(args)
      File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 187, in main
        raise cast(Exception, err).with_traceback(traceback)
      File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm\core.py", line 182, in main
        f(options.project, options)
      File "C:\Users\user\.local\pipx\venvs\pdm\lib\site-packages\pdm_packer\command.py", line 120, in handle
        zipapp.create_archive(
      File "C:\Python\lib\zipapp.py", line 111, in create_archive
        raise ZipAppError("Source does not exist")
    zipapp.ZipAppError: Source does not exist

Cannot pack if there are no packages? - `pdm add colorama` 
(why not use without packages) 
and try again

    pdm pack -m run:run -o app.zip -v
    Packing packages...
    Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove

    unearth: Downloading <Link https://files.pythonhosted.org/packages/77/8b/7550e87b2d308a1b711725dfaddc19c695f8c5fa413c640b2be01662f4e6/colorama-0.4.5-py2.py3-none-any.whl (from None)> to U:\Temp\pdm-build-42ueqwgg\colorama-0.4.5-py2.py3-none-any.whl
      v Install colorama 0.4.5 successful

      All complete!
    Packages are prepared at U:\Temp\pdm-pack-1trs0fvn\lib
    Creating zipapp...
    Zipapp is generated at app.zip

`app.zip` structure

            colorama
            __main__.py

no `run.py` file

    pdm pack --help
    Usage: pdm pack [-h] [-v] [-g] [-p PROJECT_PATH] [-m MAIN] [-o OUTPUT] [-c] [--pyc] [--no-py] [-i INTERPRETER] [--exe]

    Pack the packages into a zipapp

only packages without project files? then why need `-m run:run`?

pdm info && pdm info --env

    pdm info && pdm info --env
    PDM version:
      2.0.0
    Python Interpreter:
      C:\Python\python.exe (3.10)
    Project Root:
      z:/testapp
    Project Packages:
      z:\testapp\__pypackages__\3.10
    {
      "implementation_name": "cpython",
      "implementation_version": "3.10.5",
      "os_name": "nt",
      "platform_machine": "AMD64",
      "platform_release": "10",
      "platform_system": "Windows",
      "platform_version": "10.0.19044",
      "python_full_version": "3.10.5",
      "platform_python_implementation": "CPython",
      "python_version": "3.10",
      "sys_platform": "win32"
    }

**Comment by frostming** [comment]
> If you have code to run in your project, the project itself should be installed into `__pypackages__` as well. Make sure you have set a project name in `pyproject.toml`.

**Comment by vitidev** [comment]
>should be installed into __pypackages__

how to understand it?

If I just set the project name

    [project]
    name = "appz"

it will be strange

    pdm pack -m run:run -o app.zip -v
    Packing packages...
    Synchronizing working set with lock file: 1 to add, 0 to update, 0 to remove

    unearth: Downloading <Link https://files.pythonhosted.org/packages/77/8b/7550e87b2d308a1b711725dfaddc19c695f8c5fa413c640b2be01662f4e6/colorama-0.4.5-py2.py3-none-any.whl (from None)> to U:\Temp\pdm-build-xchq149a\colorama-0.4.5-py2.py3-none-any.whl
      v Install colorama 0.4.5 successful
    Installing the project as a package...
    pdm.termui: Preparing isolated env for PEP 517 build...
    pdm.termui: Running PEP 517 backend to build a wheel for <Link file:///Z:/testapp (from None)>
    pdm.termui: Using pip 22.1.2 from C:\Python\lib\site-packages\pip (python 3.10)
    pdm.termui: Looking in indexes: https://pypi.org/simple, https://pypilist:****@pypi.baradat.tk/simple
    pdm.termui: Collecting pdm-pep517>=1.0.0
    pdm.termui:   Using cached pdm_pep517-1.0.2-py3-none-any.whl (305 kB)
    pdm.termui: Installing collected packages: pdm-pep517
    pdm.termui: Successfully installed pdm-pep517-1.0.2
    pdm.termui: U:\Temp\pdm-build-env-t4_3i294-shared\Lib\site-packages\pdm\pep517\wheel.py:153: PDMWarning: No license files are matched with glob patterns ['LICENSES/*', 'LICEN[CS]E*', 'COPYING*', 'NOTICE*', 'AUTHORS*'].
    pdm.termui:   for license_file in self.find_license_files():
    pdm.termui:  - Adding appz-.dist-info/WHEEL
    pdm.termui:  - Adding appz-.dist-info/METADATA
    pdm.termui:  - Adding appz-.dist-info/RECORD
      v Install appz  successful

      All complete!
    Packages are prepared at U:\Temp\pdm-pack-yie_vj86\lib
    Creating zipapp...
    Zipapp is generated at app.zip

and id I placed file `__pypackages__\3.10\lib\appz\run.py `  and try again

it still won't be put in the zip

I have to build pypi package and then install it? So I can't create a zipapp just from work project?

**Comment by frostming** [comment]
```
❯ tree
.
├── __pypackages__
├── pdm.lock
├── pyproject.toml
└── run.py
```
cat `pyproject.toml`
```toml
[project]
name = "foo"
...
```
```bash
$ pdm install # this is important, to install all dependencies and the project itself
$ pdm pack -m run:run -o app.pyz
$ unzip -l app.pyz
Archive:  app.pyz
  Length      Date    Time    Name
---------  ---------- -----   ----
       31  07-16-2022 21:11   run.py
       45  07-16-2022 21:11   __main__.py
---------                     -------
       76                     2 files
```

**Comment by frostming** [comment]
The caveats are:

1. The project itself MUST be able to package(i.e. has a name)
2. The files you want to pack MUST be included in the package. We do not include all files by default, you can use the `includes` and `excludes` config to control that.

**Comment by vitidev** [comment]
@frostming 
It worked

An additional question - what about the dependencies like pyqt5 ("RECORD is not mentioned in RECORD")?
`pdm pack` tries to install package and breaks on this error.

**Comment by frostming** [comment]
> @frostming 
> 
> It worked
> 
> 
> 
> An additional question - what about the dependencies like pyqt5 ("RECORD is not mentioned in RECORD")?
> 
> `pdm pack` tries to install package and breaks on this error. The package is already exitsts in `__pypackages__`. Is it possible to skip install step?

There is a known limitation about Python zipapp, C extension modules don't work in a zipapp. i recommend not trying it.

**Comment by cvgaviao** [comment]
please @frostming , could you add an small working example project on the docs?

**Comment by frostming** [comment]
@cvgaviao Did you encounter any problem using this plugin?

**Comment by cvgaviao** [comment]
@frostming, yep.
The issues I had was due the fact that I'm coming from Java world and there a lot of python specific details that would be necessary to understand in order to use it (__main__, project.scripts and others).

It would simplify the life of a newcomer a simple functional example containing the minimal artifacts to work with PDM on all its lifecycle stages (install deps, lint, unit tests, integration tests, build package, zip and publish) ;)
