### ISSUE TITLE
Executable throws exception on numpy dependency

### ISSUE THREAD

**Issue by Gingernaut** [frostming/pdm-packer#33]
**Describe the bug**

I'm packaging up a python application that has numpy as a dependency. I package the application with `pdm pack --exe -g -p ./` - when I run `./myexecutable myFunction "arg1"` I get the following error

```
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/Users/tpeterson/Code/ai_software/luna/.venv/bin/python"
  * The NumPy version is: "1.24.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

I've tried python 3.8-3.11 and have reinstalled numpy several times. `numpy` is imported inside of "myFunction" - other python functions I call that don't have numpy as an import succeed.

**To Reproduce**
2. Run command '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
- `pdm-packer` version: latest
- Python version: 3.8
- OS: MacOS with M2 Max

**Additional context**

**Comment by frostming** [comment]
Only pure python libraries are allowed to be packed in a zipapp. Sorry.
